ARG ELK_VERSION

# https://github.com/elastic/apm-server-docker
FROM docker.elastic.co/apm/apm-server-oss:${ELK_VERSION}
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
